development:
  adapter: mysql2
  encoding: utf8
  database: devise_test_app_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: devise_test_app_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: devise_test_app_production
  pool: 5
  username: root
  password:
